### ISSUE TITLE
Minimum and Maximum Date

### ISSUE THREAD

**Issue by nabrih** [ahmed-alamir/CalendarView#1]
Hi..
Can this be added minimum and maximum date, like default CalendarView?

**Comment by ahmed-alamir** [comment]
Hi,
That should be easy to do. You can control that in the loop that fills in the days; don't fill in days before min date and stop filling once you have reached max date.

**Comment by sreeramandroid** [comment]
Hi can you help me out from this can you make minimum date for 1 year back from current date and can you update this please

**Comment by ahmed-alamir** [comment]
in `updateCalendar()` the `monthBeginningCell` variable can be limited to any past date you want. The same way the `while (cells.size() < DAYS_COUNT)` loop can also be limited to any future date.
